import { useCallback, useEffect, useState } from "react";
import {
  PdfCoordinateMapper,
  downloadFilledPdf,
  fillPdf,
  type FieldMapping,
  type MappingTemplate,
} from "pdf-coordinate-mapper";
import { createSamplePdf } from "./createSamplePdf";

// Fields that correspond to an invoice model
const INVOICE_FIELDS = [
  "invoiceNumber",
  "invoiceDate",
  "dueDate",
  "clientName",
  "clientCompany",
  "clientAddress",
  "clientEmail",
  "item1Description",
  "item1Qty",
  "item1Price",
  "item1Amount",
  "subtotal",
  "tax",
  "total",
  "notes",
];

// Sample data to fill the PDF with
const SAMPLE_DATA = {
  invoiceNumber: "INV-2026-0042",
  invoiceDate: "2026-02-16",
  dueDate: "2026-03-16",
  clientName: "Jane Smith",
  clientCompany: "Widget Co.",
  clientAddress: "123 Main St, Springfield",
  clientEmail: "jane@widgetco.com",
  item1Description: "Consulting Services",
  item1Qty: "10",
  item1Price: "$150.00",
  item1Amount: "$1,500.00",
  subtotal: "$1,500.00",
  tax: "$120.00",
  total: "$1,620.00",
  notes: "Payment due within 30 days.",
};

// Pre-built mappings so the demo works out of the box.
// These coordinates match the sample invoice PDF generated by createSamplePdf.
const PRESET_MAPPINGS: FieldMapping[] = [
  { fieldName: "invoiceNumber", page: 1, x: 470, y: 40, fontSize: 10 },
  { fieldName: "invoiceDate", page: 1, x: 470, y: 58, fontSize: 10 },
  { fieldName: "dueDate", page: 1, x: 470, y: 76, fontSize: 10 },
  { fieldName: "clientName", page: 1, x: 55, y: 110, fontSize: 11 },
  { fieldName: "clientCompany", page: 1, x: 55, y: 126, fontSize: 10 },
  { fieldName: "clientAddress", page: 1, x: 55, y: 142, fontSize: 10 },
  { fieldName: "clientEmail", page: 1, x: 55, y: 158, fontSize: 10, fontColor: "#2563eb" },
  { fieldName: "item1Description", page: 1, x: 55, y: 204, fontSize: 10 },
  { fieldName: "item1Qty", page: 1, x: 320, y: 204, fontSize: 10 },
  { fieldName: "item1Price", page: 1, x: 380, y: 204, fontSize: 10 },
  { fieldName: "item1Amount", page: 1, x: 490, y: 204, fontSize: 10 },
  { fieldName: "subtotal", page: 1, x: 490, y: 360, fontSize: 10 },
  { fieldName: "tax", page: 1, x: 490, y: 380, fontSize: 10 },
  { fieldName: "total", page: 1, x: 490, y: 400, fontSize: 12, fontColor: "#16a34a" },
  { fieldName: "notes", page: 1, x: 55, y: 442, fontSize: 10, fontColor: "#6b7280" },
];

export default function App() {
  const [pdfSource, setPdfSource] = useState<string | null>(null);
  const [mappings, setMappings] = useState<FieldMapping[]>(PRESET_MAPPINGS);
  const [savedTemplate, setSavedTemplate] = useState<Omit<MappingTemplate, "id"> | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"mapper" | "fill">("mapper");

  // Generate the sample PDF on mount
  useEffect(() => {
    createSamplePdf().then(setPdfSource);
  }, []);

  const handleSave = useCallback((template: Omit<MappingTemplate, "id">) => {
    setSavedTemplate(template);
    console.log("Template saved:", template);
    alert(`Template "${template.name}" saved with ${template.mappings.length} mappings.`);
  }, []);

  // Fill and preview
  const handlePreview = useCallback(async () => {
    if (!pdfSource) return;
    const bytes = await fillPdf(pdfSource, mappings, SAMPLE_DATA);
    const blob = new Blob([bytes.buffer as ArrayBuffer], { type: "application/pdf" });
    const url = URL.createObjectURL(blob);
    setPreviewUrl(url);
  }, [pdfSource, mappings]);

  // Fill and download
  const handleDownload = useCallback(async () => {
    if (!pdfSource) return;
    await downloadFilledPdf(pdfSource, mappings, SAMPLE_DATA, "invoice-filled.pdf");
  }, [pdfSource, mappings]);

  if (!pdfSource) {
    return <div style={{ padding: 40, fontFamily: "sans-serif" }}>Generating sample PDF...</div>;
  }

  return (
    <div style={{ maxWidth: 960, margin: "0 auto", padding: "24px 16px", fontFamily: "sans-serif" }}>
      <h1 style={{ fontSize: 22, marginBottom: 4 }}>pdf-coordinate-mapper Example</h1>
      <p style={{ color: "#6b7280", fontSize: 14, marginTop: 0 }}>
        Interactive invoice mapping demo. Click on the PDF to place field markers,
        then switch to the Fill &amp; Download tab to see the result.
      </p>

      {/* Tab bar */}
      <div style={{ display: "flex", gap: 0, marginBottom: 16, borderBottom: "2px solid #e5e7eb" }}>
        {(["mapper", "fill"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            style={{
              padding: "8px 20px",
              fontSize: 14,
              border: "none",
              borderBottom: activeTab === tab ? "2px solid #2563eb" : "2px solid transparent",
              background: "none",
              color: activeTab === tab ? "#2563eb" : "#6b7280",
              fontWeight: activeTab === tab ? 600 : 400,
              cursor: "pointer",
              marginBottom: -2,
            }}
          >
            {tab === "mapper" ? "1. Map Fields" : "2. Fill & Download"}
          </button>
        ))}
      </div>

      {/* ---------- Mapper Tab ---------- */}
      {activeTab === "mapper" && (
        <div>
          <p style={{ fontSize: 13, color: "#9ca3af", margin: "0 0 12px" }}>
            Select a field from the dropdown, then click on the PDF to place it.
            Pre-built mappings are loaded so you can jump straight to filling.
          </p>
          <PdfCoordinateMapper
            pdfSource={pdfSource}
            fieldNames={INVOICE_FIELDS}
            initialMappings={PRESET_MAPPINGS}
            onChange={setMappings}
            onSave={handleSave}
            templateName="Invoice Template"
            scale={1.3}
          />
        </div>
      )}

      {/* ---------- Fill & Download Tab ---------- */}
      {activeTab === "fill" && (
        <div>
          <h2 style={{ fontSize: 16, marginBottom: 8 }}>Sample Data</h2>
          <table
            style={{
              borderCollapse: "collapse",
              fontSize: 13,
              width: "100%",
              marginBottom: 16,
            }}
          >
            <thead>
              <tr style={{ borderBottom: "1px solid #d1d5db", textAlign: "left" }}>
                <th style={{ padding: "4px 8px" }}>Field</th>
                <th style={{ padding: "4px 8px" }}>Value</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(SAMPLE_DATA).map(([key, val]) => (
                <tr key={key} style={{ borderBottom: "1px solid #f3f4f6" }}>
                  <td style={{ padding: "4px 8px", fontFamily: "monospace", color: "#4b5563" }}>
                    {key}
                  </td>
                  <td style={{ padding: "4px 8px" }}>{val}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <div style={{ display: "flex", gap: 12, marginBottom: 20 }}>
            <button
              onClick={handlePreview}
              style={{
                padding: "8px 20px",
                fontSize: 14,
                background: "#f3f4f6",
                border: "1px solid #d1d5db",
                borderRadius: 4,
                cursor: "pointer",
              }}
            >
              Preview Filled PDF
            </button>
            <button
              onClick={handleDownload}
              style={{
                padding: "8px 20px",
                fontSize: 14,
                background: "#2563eb",
                color: "#fff",
                border: "none",
                borderRadius: 4,
                cursor: "pointer",
              }}
            >
              Download Filled PDF
            </button>
          </div>

          <p style={{ fontSize: 13, color: "#9ca3af" }}>
            Active mappings: {mappings.length} | Template saved:{" "}
            {savedTemplate ? `"${savedTemplate.name}"` : "No"}
          </p>

          {previewUrl && (
            <div style={{ marginTop: 12 }}>
              <h3 style={{ fontSize: 14, marginBottom: 8 }}>Preview</h3>
              <iframe
                src={previewUrl}
                title="Filled PDF Preview"
                style={{ width: "100%", height: 600, border: "1px solid #e5e7eb", borderRadius: 4 }}
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
